[package]
name = "actor"
version = "0.1.0"
authors = ["Roland Kuhn <rk@rkuhn.info>"]
edition = "2018"

[dependencies]
derive_more = "0.99.11"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "sync"] }
